version: '3.7'

services:
  postgres:
    image: postgres
    container_name: sense_news_db
    restart: always
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
      POSTGRES_USER: root
      POSTGRES_DB: sense_news
    ports:
      - "15433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: sense_news_db_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: "joni.oliveira89@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16544:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
